### ISSUE TITLE
save model to bucket after every epoch so runs can be ended early

### ISSUE THREAD

**Issue by Josh-Joseph** [mit-quest/necstlab-damage-segmentation#23]

**Comment by rak5216** [comment]
https://keras.io/callbacks/#modelcheckpoint

fill-in `period=<epoch freq.>` in `ModelCheckpoint` in `train_segmentation_model.py`

**Comment by rak5216** [comment]
@Josh-Joseph closing without addressing, as current method of solving best model is preferred. Noted that it was considered though.
