### ISSUE TITLE
Improving documentation on each run

### ISSUE THREAD

**Issue by CarolinaFurtado** [mit-quest/necstlab-damage-segmentation#82]
First idea that comes to mind would be to add an input argument for debugging/ tracking purpose of a specific run, such as: 

python3 train_segmentation_model.py --gcp-bucket gs://necstlab-sandbox --config-file configs/config_sandbox/tf_version_debug//train-small-3class_tfversion_debug.yaml **--message "trial run to test something"**
(defaulted to None)

Then this information would be added to the metadata file. 

It would be helpful when debugging and also if we are running many things at the same time. 
Thoughts? @Josh-Joseph @rak5216

**Comment by CarolinaFurtado** [comment]
We could also add hardware and software versions of whatever is being used

**Comment by CarolinaFurtado** [comment]
###  System and version information

created a file for systemrelated information: `metadata_sys.yaml`
it includes: 
- linux version, 
- ram
- cpu
- gpu
- host
- python, tensorflow and segmentation_models versions

![image](https://user-images.githubusercontent.com/43469359/98279454-f5270600-1f67-11eb-8914-c3bfe3f594c7.png)

### Message
Also, added a new argument to train_segmentation_model.py: --message (default to None)

```
    argparser.add_argument(
        '--message',
        type=str,
        default=None,
        help='A str message the used wants to leave, the default is None.')
```

This information is added to the `metadata.yaml` file 
![image](https://user-images.githubusercontent.com/43469359/98279854-80080080-1f68-11eb-8ea2-4a5ed3e867a2.png)

will do the same for `test_segmentation_model.py`, `train_segmentation_prediction_thresholds.py` and `infer_segmentation.py`

**Comment by CarolinaFurtado** [comment]
### Train_threshold
joined to output file: `output_file_name = 'model_thresholds_' + datetime.now(pytz.UTC).strftime('%Y%m%dT%H%M%SZ') + '.yaml'`

    output_data = {
        'final_trained_prediction_thresholds': trained_prediction_thresholds,
        'metadata': metadata,
        'metadata_sys': metadata_sys
    }

    with Path(train_thresh_id_dir, output_file_name).open('w') as f:
        yaml.safe_dump(output_data, f)

![image](https://user-images.githubusercontent.com/43469359/98302996-662be500-1f8b-11eb-875d-ebe2db9a60a8.png)

### Test
New file: `metadata_sys_file_name = 'metadata_sys_' + test_datetime + '.yaml'
`
![image](https://user-images.githubusercontent.com/43469359/98303066-8491e080-1f8b-11eb-905b-c5f094bfd582.png)

### Infer
new file: `metadata_sys_file_name = 'metadata_sys_' + infer_datetime + '.yaml'`

![image](https://user-images.githubusercontent.com/43469359/98303122-9c696480-1f8b-11eb-9183-45493a6d0f16.png)

**Comment by CarolinaFurtado** [comment]
Should I just add the `metadata_sys `to the `metadata `file that already exists? Might become to messy, since the files have a lot of information already. 

@rak5216 @Josh-Joseph, comments on this topic?

**Comment by rak5216** [comment]
three thumbs up! i like this! let's put everything into one metadata file, especially for pretrained models and transferring their details. i think simplest way is fine: take the `metadata_system` (change to 'system') and:

```
metadata = {
    .....
    'metadata_system': metadata_system
}
```
and then in train thresholds the `output_data` lines don't change since `metadata_system` is already inside `metadata`, leaving it as follows:
output_data = {
    'final_trained_prediction_thresholds': trained_prediction_thresholds,
    'metadata': metadata
}


also, it would be super cool to make the `message` the ssh window title while a given script is running so it's easy to manage several windows at once. but that doesn't seem straightforward

**Comment by CarolinaFurtado** [comment]
just joined the `matedata_system` to `metadata`! good to go once the other pull request is approved.
