### ISSUE TITLE
Tracking Epoch Time

### ISSUE THREAD

**Issue by BrendenBarbour** [mit-quest/necstlab-damage-segmentation#90]
Need to write a custom callback function to find the time per epoch and other potentially important information during the training of the model.

**Comment by CarolinaFurtado** [comment]
![image](https://user-images.githubusercontent.com/43469359/102953902-56675200-44a0-11eb-89a2-f3a57837e43a.png)
![image](https://user-images.githubusercontent.com/43469359/102953954-73038a00-44a0-11eb-86e4-aa0620b7309c.png)
