### ISSUE TITLE
Clean the code in model.py

### ISSUE THREAD

**Issue by CarolinaFurtado** [mit-quest/necstlab-damage-segmentation#91]
e.g. put the if statements into dictionaries outside de main function

**Comment by CarolinaFurtado** [comment]
@BrendenBarbour I created a branch for this and started working on it. Want to follow up? 
We can also open this up to more general cleaning, not just models.py
@rak5216 what's your take on this?

**Comment by BrendenBarbour** [comment]
I created a branch as well to do this but your implementation is much more elegant and high level. I would recommend the comment on the mechanics of the libraries more explicitly for the benefit of less experienced users. I would be more than happy to do so myself in the future. 

I think this is a good idea for the rest of our code as well as a personal goal of mine is to get less experienced users acquanted with the repository and workflow.

**Comment by CarolinaFurtado** [comment]
Oh, sorry about that! I did not understand that you were also working on this already. Ok, cool, I'll make sure I add more comments from now on. Fell free to modify the branch as you see fit or to expand the same ideas to other parts od the code

**Comment by CarolinaFurtado** [comment]
## train: if no dataset exists, gives error
![image](https://user-images.githubusercontent.com/43469359/102364847-e9762880-3f84-11eb-96c3-7de981655372.png)

## train: if no pretrained model exists, gives error 
![image](https://user-images.githubusercontent.com/43469359/102365122-3823c280-3f85-11eb-9ddf-ed73374a8b10.png)

## train thresholds: if no model exists, gives error
![image](https://user-images.githubusercontent.com/43469359/102365522-a49ec180-3f85-11eb-81ce-c77ce26d4e90.png)

## train thresholds: if no datasets exists, gives error
![image](https://user-images.githubusercontent.com/43469359/102365770-eaf42080-3f85-11eb-8062-c8c865952cbb.png)

## plots ok
![image](https://user-images.githubusercontent.com/43469359/102364642-b16ee580-3f84-11eb-9ce8-bdb9acf103bd.png)
![image](https://user-images.githubusercontent.com/43469359/102364704-c0559800-3f84-11eb-988f-cd8b65c1ccb4.png)

## right model selected - yes
no image but it selects the right model depending on the model name 

## all workflowsteps work? yes
### train
![image](https://user-images.githubusercontent.com/43469359/102367177-73bf8c00-3f87-11eb-845c-b469204b1d57.png)

### train_thresholds
![image](https://user-images.githubusercontent.com/43469359/102367883-41625e80-3f88-11eb-9fa6-7d4ad18dbbb7.png)

### test
![image](https://user-images.githubusercontent.com/43469359/102368299-b2097b00-3f88-11eb-87ca-352a600b00eb.png)
